---

- name: Install nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: Disable default server
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Create Nginx Sites
  template: src="{{ item }}.conf.j2"
            dest="/etc/nginx/sites-available/{{ item }}.conf"
  with_items: nginx_sites

- name: Enable Ngix Sites
  file: src="/etc/nginx/sites-available/{{ item }}.conf"
        dest="/etc/nginx/sites-enabled/{{ item }}.conf"
        owner=root
        group=root
        state=link
  with_items: nginx_sites
  notify: reload nginx


