---

- name: Add HHVM repo key
  shell: wget -O - http://dl.hhvm.com/conf/hhvm.gpg.key | sudo apt-key add -

- name: Add HHVM repo
  shell: echo deb http://dl.hhvm.com/ubuntu {{ ansible_distribution_release }} main | sudo tee /etc/apt/sources.list.d/hhvm.list

- name: Update apt
  apt: update_cache=yes

- name: Install HHVM
  apt: name="hhvm" state=latest
  notify: start hhvm

- name: Configure HHVM FastCGI daemon
  template: src=hhvm-server.ini.j2 dest=/etc/hhvm/server.ini
  notify: restart hhvm

- name: Configure HHVM php.ini file
  template: src=hhvm-php.ini.j2 dest=/etc/hhvm/php.ini
  notify: restart hhvm