---

- name: Add MariaDB MySQL apt-key
  apt_key: url="http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search={{ keyserver_fingerprint }}"
           state=present

- name: Add MariaDB MySQL deb and deb-src
  apt_repository: repo="{{ item }}" state=present
  with_items:
  - "deb http://{{ mirror }}/mariadb/repo/{{ version }}/ubuntu {{ ansible_distribution_release }} main"
  - "deb-src http://{{ mirror }}/mariadb/repo/{{ version }}/ubuntu {{ ansible_distribution_release }} main"

- name: Install MariaDB MySQL server
  apt: name=mariadb-server state=present
  notify: disable starting mariadb on boot

- name: Configure MariaDB server
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
  notify: 
   - restart mariadb
   - create/update mariadb debian-sys-maint user
   - execute the creation script