---

- name: Download Composer
  shell: curl -sS https://getcomposer.org/installer | hhvm --php -dHttp.SlowQueryThreshold=30000
  sudo: no

- name: Move Composer to Bin
  shell: mv composer.phar /usr/local/bin/composer.phar

- name: Use HHVM for Composer
  template: src=hhvm-composer.j2 dest=/usr/local/bin/composer
            mode=0755

- name: Update Composer
  shell: composer self-update
  environment:
   LC_ALL: en_US.UTF-8
   LANG: en_US.UTF-8

- name: Add ~/.composer/vendor/bin to PATH
  lineinfile:
    dest=/etc/environment
    state=present
    backrefs=yes
    regexp='PATH=(["]*)((?!.*?{{ composer_bin_path }}).*?)(["]*)$'
    line="PATH=\1\2:{{ composer_bin_path }}\3"