---

- name: Download Composer
  shell: curl -sS https://getcomposer.org/installer | hhvm --php -dHttp.SlowQueryThreshold=30000
  sudo: no

- name: Move Composer to Bin
  shell: mv composer.phar /usr/local/bin/composer.phar

- name: Use HHVM for Composer
  template: src=hhvm-composer.j2 dest=/usr/local/bin/composer
            mode=0755

- name: Update Composer
  shell: composer self-update